### PR TITLE
Fix execute command

### PR DESCRIPTION
**Pull request by shiftgeist**

### CODE REVIEW

**Comment by tsdgeos** [comment]
Thanks for your contribution :smiley:

This repository is a mirror of a KDE repository. This means that developers are not looking at pull requests created in GitHub, so I'm closing this pull request (actually a bot is doing it).
Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Comment by shiftgeist** [comment]
Then why are pull request even allowed here?

**Comment by nicolas17** [comment]
GitHub doesn't support disabling pull requests.

**Comment by shiftgeist** [comment]
Thats an oof

Are github pull request templates a thing?

**Pull request closed without merging**
