### PR TITLE
Add REHL to INSTALLATION.md

### PR DESCRIPTION
**Pull request by chase9**

### CODE REVIEW

**Comment by beojan** [comment]
It should be RHEL (Red Hat Enterprise Linux), not REHL.

**Comment by chase9** [comment]
Thanks, just fixed it.

**Comment by psifidotos** [comment]
PRs are reviewed only through: https://invent.kde.org/plasma/latte-dock

**Comment by chase9** [comment]
PR here: https://invent.kde.org/plasma/latte-dock/-/merge_requests/7

**Pull request closed without merging**
